//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameland.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gamesData
    {
        public string gameName { get; set; }
        public Nullable<int> gamePrice { get; set; }
        public string productType { get; set; }
        public string gameType { get; set; }
        public string gamesImg { get; set; }
        public Nullable<int> downloads { get; set; }
    }
}
