//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameland.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class forGameLandEntities1 : DbContext
    {
        public forGameLandEntities1()
            : base("name=forGameLandEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminData> adminDatas { get; set; }
        public virtual DbSet<moviesData> moviesDatas { get; set; }
        public virtual DbSet<usersData> usersDatas { get; set; }
        public virtual DbSet<specialOfferData1> specialOfferData1 { get; set; }
        public virtual DbSet<gamesData> gamesDatas { get; set; }
        public virtual DbSet<seriesData> seriesDatas { get; set; }
        public virtual DbSet<subscriptionsData> subscriptionsDatas { get; set; }
        public virtual DbSet<cartData> cartDatas { get; set; }
        public virtual DbSet<recentlyPurchaseProduct> recentlyPurchaseProducts { get; set; }
        public virtual DbSet<specialOfferData> specialOfferDatas { get; set; }
        public virtual DbSet<messageBoxData1> messageBoxData1 { get; set; }
    }
}
