//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameland.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviesData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public moviesData()
        {
            this.specialOfferDatas = new HashSet<specialOfferData>();
        }
    
        public string movieName { get; set; }
        public Nullable<int> moviePrice { get; set; }
        public string productType { get; set; }
        public string movieType { get; set; }
        public string movieImg { get; set; }
        public Nullable<int> downloads { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<specialOfferData> specialOfferDatas { get; set; }
    }
}
