//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameland.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recentlyPurchaseProduct
    {
        public int orderID { get; set; }
        public string userName { get; set; }
        public string purchaseName { get; set; }
        public string purchaseImg { get; set; }
        public string purchaseType { get; set; }
        public Nullable<int> purchasePrice { get; set; }
    
        public virtual usersData usersData { get; set; }
    }
}
