//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameland.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seriesData
    {
        public string seriesName { get; set; }
        public Nullable<int> seriesPrice { get; set; }
        public string productType { get; set; }
        public string seriesType { get; set; }
        public string seriesImg { get; set; }
        public Nullable<int> downloads { get; set; }
    }
}
