//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameland.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialOfferData
    {
        public string productName { get; set; }
        public string productCategories { get; set; }
        public string productType { get; set; }
        public Nullable<int> originalPrice { get; set; }
        public Nullable<int> offerPrice { get; set; }
        public string offerImg { get; set; }
    }
}
